version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: studentmanagement
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentmanagement?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&autoReconnect=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root 
      SPRING_DATASOURCE_PASSWORD: root1234

volumes:
  mysql_data: